---
title: "Report: Survival analysis"
output: 
  pdf_document:
    latex_engine: pdflatex
  html_document:
    toc: true
    toc_float: true
    code_folding: show
always_allow_html: yes
df_print: kable
params:
  outfolder: ""
  pdata: ""
  covclass: ""
  refcov: ""
  covord: ""
  event: ""
  timeevent: ""
date: "`r format(Sys.time(), '%d %B, %Y')`"
---
In this document are reported the result of the Survival analysis of the samples considering the classes of the attributes **`r params$refcov)`** file.

```{r setup, include=FALSE, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
knitr::opts_chunk$set(echo = TRUE)
library("dplyr")
library("ggplot2")
library("viridis")
library("survival")
library("survminer")
library("broom")
```

```{r reading, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
# Output folder creation
outf = paste0(params$outfolder, "05_Statistical_Analysis/")
dir.create(outf)

# Table containing the sample attributes
phenoData <- read.delim(params$pdata, row.names=1, check.names = F)

# List reporting the class of each sample attribute
covariates <- read.delim(params$covclass)

# Identification of the levels of the reference sample attribute
refcov <- params$refcov
cov_class <- levels(phenoData[,refcov])

# Definition of all possible combinations of the reference sample attribute levels
comparisons <- combn(cov_class, m=2)
totest_p <- list()
for(i in 1:ncol(comparisons)){totest_p[[i]] <- comparisons[,i] }

# Set the order of sample classes in the plots
covord <- params$covord
if(length(covord) == 1){covord = cov_class}
phenoData[,refcov] <- factor(phenoData[,refcov], levels = covord)

# Columns reporting the survival data
timeevent <- params$timeevent
event <- params$event
```

```{r setclass, echo=FALSE, message=FALSE, warning=FALSE, results='asis'} 
#### Defining the class of the sample attribute
  for(i in 1:ncol(phenoData)){
    if(as.character(covariates[,2][i]) == "factor"){
      phenoData[, i] = as.factor(phenoData[, i])}
    else{
      class(phenoData[, i]) = as.character(covariates[,2][i])}
  }
```

## Survival analysis
```{r survanalysis, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
## Create a survival object
surv_object <- Surv(time = phenoData[,timeevent], event = phenoData[,event])
fit1 <- survfit(surv_object ~ refcov, data = phenoData)
summary(fit1)

## KM plot with log-rank p-value
ggsurvplot(fit1, data = ovarian, pval = T, conf.int = T, cumevents=F, cumcensor = F, risk.table=T, risk.table.col = "strata", ggtheme = theme_bw())
```

```{r fitall, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
# Fit a Cox proportional hazards model
fit.coxph <- coxph(surv_object ~ rx + resid.ds + age + ecog.ps, 
                   data = phenoData)
ggforest(fit.coxph, data = phenoData)

tidy(fit.coxph)
augment(fit.coxph, data=phenoData)
glance(fit.coxph)
```

## Output files
The following output files were generated:

All the output file were generated in the folder **05_Statistical_Analysis**